# Generated by Django 6.0.1 on 2026-01-12 16:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('task', '0003_rename_task_txcvask'),
        ('todolist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='txcvask',
            new_name='Task',
        ),
    ]
